apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: byfmein2m-nodejs
  janus-idp.io/tekton: byfmein2m-nodejs
  backstage.io/kubernetes-id: byfmein2m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: byfmein2m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
