apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: byfmein2m-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: byfmein2m-nodejs 
  name: byfmein2m-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: byfmein2m-nodejs 
